### ISSUE TITLE
Add prompt for make file options

### ISSUE THREAD

**Issue by arithmetric** [phase2/generator-gadget#1]
Let's add a prompt for the type of make file/approach to use.

Currently Grunt Drupal Tasks ships with an "ini" formatted Drush make file. We should be able to also support yaml formatted Drush make files.

With some work upstream, we could also support a Composer-based option that replaces Drush make in the build process. (Depends on changes to Grunt Drupal Tasks. See: https://github.com/phase2/grunt-drupal-tasks/pull/133)

**Comment by arithmetric** [comment]
See also: https://github.com/drupal-composer/drupal-project

**Comment by arithmetric** [comment]
See also: http://tim.millwoodonline.co.uk/post/124913346140/drupal-8-composer

**Comment by arithmetric** [comment]
Continued support of the ini format is likely not a priority, and with #13 we will switch to use yaml by default, so this issue will focus on supporting Composer-based make options once Grunt Drupal Tasks supports this.

**Comment by grayside** [comment]
It is no longer a choice in Drupal 8, so we've baked this in as implicit to the D7/D8 decision.
