### ISSUE TITLE
Need a different composer.json for Drupal 8

### ISSUE THREAD

**Issue by jhedstrom** [phase2/generator-gadget#51]
Over in https://github.com/phase2/grunt-drupal-tasks/pull/237 a Drupal-8-specific `composer.json` file was added to get tests passing. Gadget templates probably need a similar pattern where core-version-specific files would take precedence.

**Comment by grayside** [comment]
`app/index.js:92` copies `app/templates/gdt` into the root of the project. `app/index.js:111` copies files specific to a distro & version into root. E.g., the directory at `templates/drupal/<distro>/<version>`.

I'm not sure if conflicts would occur, but it seems like it would be easiest for now to leave the composer.json in place in the templates/gdt directory, and add a drupal/8.x version to override it.
