### ISSUE TITLE
Theme Generator

### ISSUE THREAD

**Issue by danielnv18** [phase2/generator-gadget#9]
What do you think about add the ability to generate a theme?

If the answer is yes, there is this yeoman project to generate drupal themes https://github.com/frontend-united/generator-drupal-theme and you can see an implementation of that generator here ->https://github.com/Snugug/generator-aurora

so... what do you think?

**Comment by grayside** [comment]
Hi Daniel,

Gadget isn't trying to compete on theme generation. In a lot of ways that's a separate specialty that is much more focused on Drupal theming and frontend best practices, whereas gadget has a much stronger focus on general Drupal development and operations.

Phase2 has a sibling project to Gadget you may be interested in: https://github.com/phase2/generator-pattern-lab-starter.
